### ISSUE TITLE
Add new Finnish names to Symphyta

### ISSUE THREAD

**Issue by laihoel** [luomus/meta#111]
Juho Paukkunen has asked us to load new Finnish Symphyta names (~700) to the database. These have been published in Sahlbergia.
It would be nice to have these downloaded before 31.12.2024 so they would be included in the new checklist.

Tea discusses with Tapani if he could help us - show Markus how he could do it in the future.

The file Juho provided:
https://helsinkifi-my.sharepoint.com/:x:/g/personal/ellaiho_ad_helsinki_fi/EQ1s8SUVGR5InMYLgmZAfroBm-n9NEkC2-fvyXbf1hAjxQ?e=nNC61j

**Comment by mikkohei13** [comment]
Few questions:

- There's "Uusi suomenkielinen nimi" and "Uudistettu nimi". Which is the valid one?
- There are names for few genera, like "Athalia sp." = suomenkekäläinen / omatarpistiäinen. Why for only some, and why in singular form? A mistake?
- There are some names like "Euura sp. nr miltonota > halo". What are these?

**Comment by wkmor1** [comment]
I am pretty sure I could use Chrome DevTools Protocol to automate this and do a batch update just using the taxoneditor UI and not have to touch the database.

**Comment by laihoel** [comment]
@mikkohei13 Mikko, I haven't checked the list yet but I was planning to edit it in a format that has MX-codes so these questions will be resolved then (discussing with Juho).

**Comment by laihoel** [comment]
@wkmor1 This sounds interesting. I'll edit the list then and you could try adding the names?

**Comment by wkmor1** [comment]
Yep, can do. Adding a column for MX.codes would make it easier. Although if we trust the names in the first column as they are and they align unambiguously with what is in the taxon database now, then we could just go off that?

**Comment by laihoel** [comment]
I'll ask Juho if they have downloaded the name list from us.

**Comment by Tea-shroom** [comment]
Hi, so Will could do this after adding the MX-codes to those names?

**Comment by wkmor1** [comment]
Yep, pretty sure I can

**Comment by wkmor1** [comment]
Here is these data joined to what is the taxon database now. 38 of them dont have matches in the DB and one (Euura lanatae) is matched twice. 

[symphyta.csv](https://github.com/user-attachments/files/17521155/symphyta.csv)

**Comment by laihoel** [comment]
I did the same job it seems :) Here's my version: https://helsinkifi-my.sharepoint.com/:x:/g/personal/ellaiho_ad_helsinki_fi/Eb07M1fbUVpGl6TTfD8wLLoB7aquc6lD02Pkb_55R80kMA?e=0T3Zyp 

I asked Juho to check those that didn't have a match and add the names with TaxonEditor.

I have also edited so that there's only one Finnish name column (the Uudistettu nimi is the one to be used if there were two options).

**Comment by wkmor1** [comment]
Did you ask him about the status of "Euura lanatae"? it seems to be both species and an infra-species at the moment

**Comment by laihoel** [comment]
The species one is the valid taxon. The other one is hidden (shouldn't have the same name anyway, I'll inform him).

**Comment by wkmor1** [comment]
So just to confirm. The idea is that if the old Finnish name is different to the new one it should be kept as an "Other common names (FI)" with the new one replacing it as "Primary vernacular name"? Or does the old name go to one of the other fields?

**Comment by laihoel** [comment]
@wkmor1 The old Finnish name should go to "obsolete common names" field. Just checked this from Juho.

**Comment by wkmor1** [comment]
@laihoel OK then. So is now ready to go then, based on your most recent spreadsheet?

**Comment by wkmor1** [comment]
Wrote a script https://github.com/luomus/meta/blob/main/scripts/symphyta.R
It is running now

**Comment by wkmor1** [comment]
Script finished running. I think it worked as expected. I checked a few random taxa and they seem to have the correct vernacular and obsolete now when you look at them from the taxon editor. The taxon cards on laji.fi still have the same names but I guess it takes a while for the updates to show up? Someone should double check that it all looks good before we close.

**Comment by laihoel** [comment]
I did some random checks too and for me it seems that new Finnish names and obsolete Finnish names have been added correctly.

**Comment by Tea-shroom** [comment]
[celebrate]     von Bonsdorff-Salminen, Tea K reacted to your message:
________________________________

**Comment by laihoel** [comment]
Names are now visible also in Laji.fi. I'll close this task.
