### ISSUE TITLE
Update eBird data on DW

### ISSUE THREAD

**Issue by mikkohei13** [luomus/meta#20]
Update eBird data to DW.

Files are on the network drive at \public_admin\Lajitietokeskus\ebird

Documentation on wiki, at least on page https://wiki.helsinki.fi/xwiki/bin/view/luomusict/Luomus%20Biodiversity%20Informatics%20Unit/IT%20Systems/DW%20%20Data%20warehouse%20%20Tietovarasto%20%20Laji-ETL%20%20dw.laji.fi/eBird%20data%20to%20DW/#

**Comment by esko-piirainen** [comment]
Data has been updated
