### ISSUE TITLE
Add new LajiGIS fields in the observation viewer

### ISSUE THREAD

**Issue by laihoel** [luomus/meta#72]
These 3 fields can be added both to the public Laji.fi & PAP

- [ ] **monitoringSite** - Seurattava (LG_KOHDE.SEURATTAVA) – kertoo, onko kohde seurantakohde vai ei, käytössä luokittelu ei/kyllä, pakollinen tieto LajiGISissä

- [ ] **potentialGrowthArea** - Lajin potentiaalinen kasvuala (LG_LAJIHAV. POT_KASVUALA) – lajihavainnon tieto, lukuarvo, täytetty osalle havainnoista

- [ ] **potentialGrowthAreaClear** - Paljas potentiaalinen kasvuala (LG_LAJIHAV.PALJAS_POT_KASVUALA) - lajihavainnon tieto, lukuarvo, täytetty osalle havainnoista

**Comment by mikkohei13** [comment]
@laihoel Do we have example data of these already? Why / for who they are needed?

**Comment by laihoel** [comment]
Yes, this is LajiGIS data and a wish from Metsähallitus. I didn't know these should show up automatically @MLumme
