### ISSUE TITLE
Increase observer name limit and update intro text

### ISSUE THREAD

**Issue by mikkohei13** [luomus/meta#87]
At https://tulokset.lintuatlas.fi/observers

- fetch top 1000 observer names instead of 100
- change intro text to "Määrät perustuvat niihin Lajitietokeskuksen tietojärjestelmiin tallennettuihin havaintoihin, joissa havainnoijan nimi on julkinen."

**Comment by MLumme** [comment]
Done, deployed in both dev and prod.

**Comment by mikkohei13** [comment]
Looks ok, marking as done since no code changes.
